export const QueryKey = {
	CURRENT_USER: 'CURRENT_USER',
	INFINITE_USER_STORY: 'INFINITE_USER_STORY',
	INFINITE_POST: 'INFINITE_POST',
	INFINITE_USER: 'INFINITE_USER',
	INFINITE_COMMENT: 'INFINITE_COMMENT',
	USER_PROFILE: 'USER_PROFILE',

	DETAIL_USER_STORY: 'DETAIL_USER_STORY',
	DETAIL_POST: 'DETAIL_POST',
};
